name: Security Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

 
     - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2
    
          # Docker image'ını build et
          - name: Build Docker image
            run: |
              docker build -t juice-shop .





