


name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

  docker-test:
    needs: build-project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t my-juice-shop .

  gitleaks-scan:
    needs: docker-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Run Gitleaks to detect secrets
        uses: gitleaks/gitleaks-action@v2.3.2
        with:
          config-path: ""
          report-format: sarif
          report-path: gitleaks.sarif

  semgrep-scan:
    needs: gitleaks-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Semgrep SAST Scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/default
          generate-sarif: true
          output: semgrep.sarif

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif
  dummy-deploy:
    needs: semgrep-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Dummy Deploy Step
        run: echo "✅ Dummy deploy işlemi başarılı bir şekilde tamamlandı."

