


name: Docker Build and Semgrep SAST with SARIF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Repository'yi checkout et
      - name: Checkout repository
        uses: actions/checkout@v4

      # Docker'ı kur
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Docker image'ı build et
      - name: Build Docker image
        run: |
          docker build -t my-docker-image .

      # Semgrep kurulum
      - name: Install Semgrep
        run: |
          python -m pip install semgrep

      # Semgrep taraması ve SARIF raporunun oluşturulması
      - name: Run Semgrep Analysis
        run: |
          docker run --rm -v $(pwd):/app my-docker-image semgrep --config auto --output results.sarif --sarif

      # SARIF raporunu yükle (GitHub'a rapor ekle)
      - name: Upload SARIF Report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif


